name: Deploy to CloudPanel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 95.216.6.6
        username: resetclub
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Load Node.js environment
          export PATH="$HOME/.nvm/versions/node/$(ls $HOME/.nvm/versions/node/ | tail -1)/bin:$PATH"
          source ~/.bashrc || true
          source ~/.profile || true
          
          # Navigate to project directory
          cd htdocs/resetclub.ma
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies and build
          npm ci
          npm run build
          
          # Restart the application
          if command -v pm2 >/dev/null 2>&1; then
            pm2 restart resetclub || pm2 start npm --name "resetclub" -- start
          else
            # Install PM2 if not available
            npm install -g pm2
            pm2 start npm --name "resetclub" -- start
          fi
          
          # Save PM2 configuration
          pm2 save || true
          
    - name: Deployment notification
      if: success()
      run: echo "Deployment completed successfully!"