name: Deploy to CloudPanel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 95.216.6.6
        username: resetclub
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd htdocs/resetclub.ma
          git pull origin main
          npm ci
          npm run build
          pm2 restart resetclub || npm start
          
    - name: Deployment notification
      if: success()
      run: echo "Deployment completed successfully!"